# Generated by Django 5.2.2 on 2025-07-24 02:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la vacuna')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('doses_required', models.PositiveIntegerField(default=1, verbose_name='Dosis requeridas')),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Días entre dosis para vacunas de múltiples aplicaciones', null=True, verbose_name='Intervalo entre dosis (días)')),
                ('age_min_months', models.PositiveIntegerField(blank=True, help_text='Edad mínima recomendada para aplicación', null=True, verbose_name='Edad mínima (meses)')),
                ('age_max_months', models.PositiveIntegerField(blank=True, help_text='Edad máxima recomendada para aplicación', null=True, verbose_name='Edad máxima (meses)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vacuna',
                'verbose_name_plural': 'Tipos de Vacunas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Número de dosis')),
                ('status', models.CharField(choices=[('applied', 'Aplicada'), ('scheduled', 'Programada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('scheduled_date', models.DateField(help_text='Fecha en que debe aplicarse la vacuna', verbose_name='Fecha programada')),
                ('applied_date', models.DateField(blank=True, help_text='Fecha real en que se aplicó la vacuna', null=True, verbose_name='Fecha de aplicación')),
                ('healthcare_provider', models.CharField(blank=True, help_text='Hospital, clínica o centro de salud', max_length=200, verbose_name='Proveedor de salud')),
                ('doctor_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del médico')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Número de lote')),
                ('reaction', models.CharField(choices=[('none', 'Ninguna'), ('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Severa')], default='none', max_length=20, verbose_name='Reacción')),
                ('reaction_notes', models.TextField(blank=True, help_text='Descripción detallada de cualquier reacción', verbose_name='Notas sobre reacciones')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vaccine_records', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccinetype', verbose_name='Tipo de vacuna')),
            ],
            options={
                'verbose_name': 'Registro de Vacuna',
                'verbose_name_plural': 'Registros de Vacunas',
                'ordering': ['-scheduled_date', '-applied_date'],
                'unique_together': {('user', 'vaccine_type', 'dose_number')},
            },
        ),
        migrations.CreateModel(
            name='VaccineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('upcoming', 'Próxima vacuna'), ('overdue', 'Vacuna vencida'), ('next_dose', 'Siguiente dosis'), ('annual_reminder', 'Recordatorio anual')], max_length=20, verbose_name='Tipo de alerta')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('alert_date', models.DateTimeField(help_text='Cuándo debe mostrarse la alerta', verbose_name='Fecha de alerta')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviada')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vaccine_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vaccines.vaccinerecord', verbose_name='Registro de vacuna')),
            ],
            options={
                'verbose_name': 'Alerta de Vacuna',
                'verbose_name_plural': 'Alertas de Vacunas',
                'ordering': ['-alert_date', '-priority'],
            },
        ),
    ]
