# Generated by Django 5.2.2 on 2025-07-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinealert',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccinetype', verbose_name='Tipo de vacuna'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='age_at_application',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad al momento de aplicación (meses)'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='vaccinerecord',
            name='reaction_treatment',
            field=models.TextField(blank=True, verbose_name='Tratamiento aplicado'),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='cdc_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos completos del CDC'),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='cvx_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código CVX (CDC)'),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='is_national_schedule',
            field=models.BooleanField(default=False, verbose_name='En calendario nacional'),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='mvx_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código MVX (Fabricante CDC)'),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='schedule_ages',
            field=models.JSONField(blank=True, default=list, verbose_name='Edades del calendario (meses)'),
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='alert_date',
            field=models.DateTimeField(verbose_name='Fecha de alerta'),
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='alert_type',
            field=models.CharField(choices=[('upcoming', 'Próxima vacuna'), ('overdue', 'Vacuna vencida'), ('next_dose', 'Siguiente dosis'), ('national_schedule', 'Calendario nacional'), ('annual_reminder', 'Recordatorio anual')], max_length=20, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='vaccine_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vaccines.vaccinerecord', verbose_name='Registro de vacuna'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='applied_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aplicación'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Médico responsable'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='healthcare_provider',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institución de salud'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='reaction_notes',
            field=models.TextField(blank=True, verbose_name='Descripción de reacciones'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='scheduled_date',
            field=models.DateField(verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='age_max_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad máxima (meses)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='age_min_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima (meses)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervalo entre dosis (días)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la vacuna'),
        ),
    ]
