# Generated by Django 5.2.2 on 2025-07-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_vaccinealert_vaccine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinealert',
            name='vaccine_type',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='age_at_application',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='manufacturer_name',
        ),
        migrations.RemoveField(
            model_name='vaccinerecord',
            name='reaction_treatment',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='cdc_data',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='cvx_code',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='is_national_schedule',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='mvx_code',
        ),
        migrations.RemoveField(
            model_name='vaccinetype',
            name='schedule_ages',
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='alert_date',
            field=models.DateTimeField(help_text='Cuándo debe mostrarse la alerta', verbose_name='Fecha de alerta'),
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='alert_type',
            field=models.CharField(choices=[('upcoming', 'Próxima vacuna'), ('overdue', 'Vacuna vencida'), ('next_dose', 'Siguiente dosis'), ('annual_reminder', 'Recordatorio anual')], max_length=20, verbose_name='Tipo de alerta'),
        ),
        migrations.AlterField(
            model_name='vaccinealert',
            name='vaccine_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vaccines.vaccinerecord', verbose_name='Registro de vacuna'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='applied_date',
            field=models.DateField(blank=True, help_text='Fecha real en que se aplicó la vacuna', null=True, verbose_name='Fecha de aplicación'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del médico'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='healthcare_provider',
            field=models.CharField(blank=True, help_text='Hospital, clínica o centro de salud', max_length=200, verbose_name='Proveedor de salud'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='reaction_notes',
            field=models.TextField(blank=True, help_text='Descripción detallada de cualquier reacción', verbose_name='Notas sobre reacciones'),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='scheduled_date',
            field=models.DateField(help_text='Fecha en que debe aplicarse la vacuna', verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='age_max_months',
            field=models.PositiveIntegerField(blank=True, help_text='Edad máxima recomendada para aplicación', null=True, verbose_name='Edad máxima (meses)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='age_min_months',
            field=models.PositiveIntegerField(blank=True, help_text='Edad mínima recomendada para aplicación', null=True, verbose_name='Edad mínima (meses)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días entre dosis para vacunas de múltiples aplicaciones', null=True, verbose_name='Intervalo entre dosis (días)'),
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la vacuna'),
        ),
    ]
