# Generated by Django 5.2.2 on 2025-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, help_text='Medicamentos, alimentos, sustancias ambientales', null=True)),
                ('reaccion', models.TextField(blank=True, help_text='Ej: rash, dificultad respiratoria, anafilaxia', null=True)),
                ('fechaPrimerEvento', models.DateField(blank=True, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='heredoFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEnfermedad', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
                ('tipoEnfermedad', models.TextField()),
                ('edadDiacnosticoEnfermedad', models.IntegerField()),
                ('estadoActual', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, help_text='Ej: lactosa, gluten, fructosa', null=True)),
                ('sintomas', models.TextField(blank=True, help_text='Síntomas experimentados y severidad', null=True)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico médico o autoinforme', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personalesNoPatologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabaquismo', models.TextField(blank=True, help_text='Tipo, frecuencia, duración en años', null=True)),
                ('alcohol', models.TextField(blank=True, help_text='Frecuencia y cantidad promedio', null=True)),
                ('actividadFisica', models.TextField(blank=True, help_text='Tipo, frecuencia semanal, intensidad', null=True)),
                ('alimentacion', models.TextField(blank=True, help_text='Tipo de dieta habitual, restricciones, hábitos', null=True)),
                ('saludMental', models.TextField(blank=True, help_text='Estrés, manejo emocional, terapia', null=True)),
                ('suenio', models.TextField(blank=True, help_text='Calidad, duración, trastornos como insomnio o apnea', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personalesPatologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEnfermedad', models.CharField(max_length=100)),
                ('fechaDiagnostico', models.DateField()),
                ('intervenciones', models.CharField(blank=True, max_length=100, null=True)),
                ('intervencionesFecha', models.DateTimeField(blank=True, null=True)),
                ('intervencionesMotivo', models.CharField(blank=True, max_length=100, null=True)),
                ('intervencionesLugar', models.TextField(blank=True, null=True)),
                ('hospitalizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('hospitalizacionFecha', models.DateTimeField(blank=True, null=True)),
                ('hospitalizacionMotivo', models.CharField(blank=True, max_length=100, null=True)),
                ('hospitalizacionLugar', models.TextField(blank=True, null=True)),
                ('hospitalizacionTratamientos', models.TextField(blank=True, null=True)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('nombreTratamientos', models.TextField(blank=True, null=True)),
                ('dosisTratamientos', models.TextField(blank=True, null=True)),
                ('reaccionesTratamientos', models.TextField(blank=True, null=True)),
                ('frecuenciaTratamientos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
