# Generated by Django 5.2.2 on 2025-08-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('tipo_estudio', models.CharField(max_length=255)),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('hallazgos', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estudios/funcional/pdf/')),
                ('video', models.FileField(blank=True, null=True, upload_to='estudios/funcional/videos/')),
                ('interpretacion_automatica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioGabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_realizacion', models.DateField()),
                ('centro_medico', models.CharField(max_length=255)),
                ('motivo_clinico', models.TextField()),
                ('resultado', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estudios/gabinete/pdf/')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='estudios/gabinete/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='estudios/gabinete/videos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_muestra', models.DateField()),
                ('laboratorio', models.CharField(max_length=255)),
                ('tecnica', models.TextField(blank=True, null=True)),
                ('valores', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='estudios/laboratorio/pdf/')),
                ('accion_medica', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
