# Generated by Django 5.2.2 on 2025-06-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test_field',
        ),
    ]
