# Generated by Django 5.2.2 on 2025-08-15 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=160)),
                ('diagnosis_date', models.DateField()),
                ('age_at_diagnosis', models.PositiveSmallIntegerField()),
                ('diagnosing_institution', models.CharField(blank=True, max_length=160)),
                ('diagnosing_physician', models.CharField(blank=True, max_length=160)),
                ('current_status', models.CharField(choices=[('CONTROLLED', 'Controlado'), ('POORLY_CONTROLLED', 'Mal controlado'), ('REMISSION', 'En remisión'), ('PROGRESSIVE', 'Progresivo')], default='CONTROLLED', max_length=24)),
                ('classification_system', models.CharField(blank=True, max_length=80)),
                ('classification_level', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='chronic.chroniccondition')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('present', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('RARE', 'Rara vez'), ('OCCASIONAL', 'Ocasional'), ('FREQUENT', 'Frecuente'), ('DAILY', 'Diaria')], default='OCCASIONAL', max_length=16)),
                ('intensity', models.CharField(choices=[('MILD', 'Leve'), ('MODERATE', 'Moderada'), ('SEVERE', 'Severa')], default='MILD', max_length=16)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='chronic.chroniccondition')),
            ],
        ),
        migrations.AddIndex(
            model_name='chroniccondition',
            index=models.Index(fields=['patient_user', 'disease_name'], name='chronic_chr_patient_19371d_idx'),
        ),
        migrations.AddIndex(
            model_name='chroniccondition',
            index=models.Index(fields=['current_status'], name='chronic_chr_current_8f3106_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complication',
            unique_together={('condition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='symptom',
            unique_together={('condition', 'name')},
        ),
    ]
