<<<<<<< HEAD

# Generated by Django 5.2.2 on 2025-07-16 21:30

# Generated by Django 5.2.2 on 2025-07-23 19:18

# Generated by Django 5.0.1 on 2025-07-22 20:28



import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings

# Generated by Django 5.2.2 on 2025-07-08 22:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('apellido_paterno', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('apellido_materno', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('phone', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('contactoEmergencia', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('photoUser', models.ImageField(blank=True, null=True, upload_to='user_photos/')),

                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('relacion', models.CharField(help_text="p.ej. 'Hijo', 'Esposa', etc.", max_length=50)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('grupoRH', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
