# Generated by Django 5.2.2 on 2025-06-26 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido_materno',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
    ]
