# Generated by Django 5.2.2 on 2025-06-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('relacion', models.CharField(help_text="p.ej. 'Hijo', 'Esposa', etc.", max_length=50)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
