# Generated by Django 5.2.2 on 2025-07-29 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactoEmergenciaNombre',
            field=models.CharField(default='Nombre del contacto', max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
    ]
