# Generated by Django 5.2.2 on 2025-08-10 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_nombrecontacoemergencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombreContacoEmergencia',
        ),
        migrations.AlterField(
            model_name='user',
            name='contactoEmergenciaNombre',
            field=models.CharField(default='Nombre del contacto', max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
    ]
