# Generated by Django 5.2.2 on 2025-07-08 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verification_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactoEmergencia',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='photoUser',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
