# Generated by Django 5.0.1 on 2025-07-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_menstruacion', models.DateField()),
                ('duracion_promedio_ciclo', models.PositiveSmallIntegerField(help_text='Días entre inicio de un sangrado y el siguiente')),
                ('duracion_promedio_sangrado', models.PositiveSmallIntegerField(help_text='Duración promedio del periodo en días')),
                ('es_regular', models.BooleanField(help_text='Ciclos regulares o irregulares')),
                ('sintomas', models.TextField(blank=True, help_text='Síntomas físicos o emocionales')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones (estrés, viajes…)')),
                ('medicacion_hormonal', models.CharField(blank=True, help_text='Medicamentos hormonales usados', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Menstrual',
                'verbose_name_plural': 'Registros Menstruales',
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_menstruacion', models.DateField()),
                ('fecha_probable_parto', models.DateField(blank=True, null=True)),
                ('nivel_riesgo', models.CharField(choices=[('low', 'Bajo'), ('moderate', 'Moderado'), ('high', 'Alto')], max_length=10)),
                ('intervenciones', models.TextField(blank=True, help_text='Controles, medicamentos o derivaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_medica', models.TextField()),
                ('recomendaciones', models.TextField(blank=True, help_text='Dieta, ejercicio…')),
                ('fecha_cita', models.DateField(blank=True, help_text='Próxima cita o análisis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gineco.pregnancy')),
            ],
            options={
                'verbose_name': 'Nota Clínica',
                'verbose_name_plural': 'Notas Clínicas',
            },
        ),
        migrations.CreateModel(
            name='PregnancyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_gestacional', models.PositiveSmallIntegerField(help_text='Mes 1–9')),
                ('sintomas_fisicos', models.TextField(blank=True, help_text='Náuseas, edemas…')),
                ('estado_emocional', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Kg', max_digits=5)),
                ('presion_arterial', models.CharField(blank=True, max_length=20)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('movimientos_fetales', models.BooleanField(help_text='Movimientos detectados')),
                ('ultrasonido', models.TextField(blank=True, help_text='Resultados de ultrasonidos')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='gineco.pregnancy')),
            ],
            options={
                'verbose_name': 'Control de Embarazo',
                'verbose_name_plural': 'Controles de Embarazo',
            },
        ),
    ]
