# Generated by Django 5.0.1 on 2025-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gineco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancycheck',
            name='ultrasonido',
            field=models.FileField(blank=True, help_text='Subir archivo de ultrasonido (PDF, imagen)', null=True, upload_to='ultrasonidos/'),
        ),
    ]
