<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-08-10 15:36

import cloudinary_storage.storage
=======
# Generated by Django 5.2.2 on 2025-08-15 06:39

import cloudinary_storage.storage
import django.db.models.deletion
>>>>>>> origin/feature/joss
import prescriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('institution', models.CharField(max_length=150)),
                ('prescribing_doctor', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('file', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='medpal/prescriptions/', validators=[prescriptions.models.validate_file_extension, prescriptions.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/feature/joss
            ],
        ),
    ]
