# Generated by Django 5.2.2 on 2025-07-18 03:24

import django.db.models.deletion
import prescriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('institution', models.CharField(max_length=150)),
                ('prescribing_doctor', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='prescriptions/', validators=[prescriptions.models.validate_file_extension, prescriptions.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
