# Generated by Django 5.2.2 on 2025-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalprescription',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
