# Generated by Django 5.2.2 on 2025-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_rename_notes_medicalprescription_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='patient_name',
            field=models.CharField(default='No registrado', max_length=150),
            preserve_default=False,
        ),
    ]
