# Generated by Django 5.2.2 on 2025-08-11 05:31

import cloudinary_storage.storage
import django.db.models.deletion
import prescriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('prescriptions', '0002_medicalprescription_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescriptions', to='accounts.perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='medpal/prescriptions/', validators=[prescriptions.models.validate_file_extension, prescriptions.models.validate_file_size]),
        ),
    ]
