# Generated by Django 5.2.2 on 2025-08-13 00:51

import cloudinary_storage.storage
import prescriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_remove_medicalprescription_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.FileField(default=1, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='medpal/prescriptions/', validators=[prescriptions.models.validate_file_extension, prescriptions.models.validate_file_size]),
            preserve_default=False,
        ),
    ]
