<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-08-10 06:28
=======
# Generated by Django 5.2.2 on 2025-08-14 23:23
>>>>>>> origin/feature/joss

import cloudinary_storage.storage
import django.db.models.deletion
import ophthalmology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OphthalmologyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('attention_type', models.CharField(blank=True, choices=[('routine', 'Routine Check-up'), ('followup', 'Chronic Condition Follow-up'), ('postop', 'Postoperative'), ('preventive', 'Preventive Screening')], max_length=20, null=True)),
                ('diagnosis', models.TextField(help_text='Detailed visual diagnosis')),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='medpal/ophthalmology/', validators=[ophthalmology.models.validate_file_extension, ophthalmology.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ophthalmology_diagnoses', to='accounts.perfil')),
            ],
        ),
    ]
