# Generated by Django 5.2.2 on 2025-07-18 03:25

import django.db.models.deletion
import ophthalmology.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OphthalmologyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('attention_type', models.CharField(blank=True, choices=[('routine', 'Routine Check-up'), ('followup', 'Chronic Condition Follow-up'), ('postop', 'Postoperative'), ('preventive', 'Preventive Screening')], max_length=20, null=True)),
                ('diagnosis', models.TextField(help_text='Detailed visual diagnosis')),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to='ophthalmology/', validators=[ophthalmology.models.validate_file_extension, ophthalmology.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ophthalmology_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
