# Generated by Django 5.2.2 on 2025-07-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophthalmologydiagnosis',
            name='patient',
        ),
        migrations.AddField(
            model_name='ophthalmologydiagnosis',
            name='patient_name',
            field=models.CharField(default='No registrado', max_length=150),
            preserve_default=False,
        ),
    ]
