# Generated by Django 5.2.2 on 2025-07-17 21:26

import cloudinary_storage.storage
import ophthalmology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ophthalmologydiagnosis',
            name='document',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='medpal/ophthalmology/', validators=[ophthalmology.models.validate_file_extension, ophthalmology.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ophthalmologydiagnosis',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
