# Generated by Django 5.2.2 on 2025-08-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ophthalmology', '0002_ophthalmologydiagnosis_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophthalmologydiagnosis',
            name='patient',
        ),
        migrations.AddField(
            model_name='ophthalmologydiagnosis',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ophthalmology_diagnoses', to='accounts.perfil'),
            preserve_default=False,
        ),
    ]
